import { type ReactNode } from 'react';
import { Navbar } from '../components/storefront/Navbar';

export default function StoreFrontLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Navbar />
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">{children}</main>
    </>
  );
}
// import type { Metadata } from 'next';

// // import './globals.css';
// // import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
// // import { extractRouterConfig } from 'uploadthing/server';
// import { Navbar } from '../components/storefront/Navbar';
// // import { ourFileRouter } from './api/uploadthing/core';

// export const metadata: Metadata = {
//   title: 'StoreFront',
//   description: 'Generated by create next app',
// };

// export default function StoreFrontLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <>
//       <Navbar />
//       {/* <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} /> */}

//       <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-6">{children}</main>
//     </>
//   );
// }
